Import('env', 'arch', 'cereal', 'messaging', 'common', 'gpucommon', 'visionipc')

libs = ['m', 'pthread', common, 'jpeg', 'OpenCL', 'yuv', cereal, messaging, 'zmq', 'capnp', 'kj', visionipc, gpucommon]

if arch == "earch64":
  libs += ['gsl', 'CB', 'adreno_utils', 'EGL', 'GLESv3', 'cutils', 'ui']
  cameras = ['cameras/camera_qcom.cc']

  env.Program('camerad', [
      'main.cc',
      'cameras/camera_common.cc',
      'transforms/rgb_to_yuv.cc',
      'imgproc/utils.cc',
      cameras,
    ], LIBS=libs)
