#!/bin/sh

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
cd $DIR

if [ -d /system ]; then
  if [ -f /EON ]; then
    export LD_LIBRARY_PATH="/data/pythonpath/third_party/snpe/earch64/:$LD_LIBRARY_PATH"
    export ADSP_LIBRARY_PATH="/data/pythonpath/third_party/snpe/dsp/"
  fi
else
  # PC
  export LD_LIBRARY_PATH="$DIR/../../third_party/snpe/x86_64-linux-clang:$DIR/../../openpilot/third_party/snpe/x86_64:$LD_LIBRARY_PATH"
fi
exec ./_dmonitoringmodeld
